# When needed to run a loop to install multiple packages use this playbook
# Tested and worked fine for Centos 8 and Ubuntu 18.04
---
- name: Provisioning Server
  hosts: all
  tasks:
   - name: Add Epel repository in CentOS
     yum:
       name: epel-release
       state: present
     when: ansible_distribution == "CentOS"

   - name: Add Universe repository in Ubuntu
     apt_repository:
       repo: deb http://archive.ubuntu.com/ubuntu focal universe
       state: present
     when: ansible_distribution == "Ubuntu"

   - name: Install multiple packages on CentOS
     yum:
       name: '{{item}}'
       state: present
     when: ansible_distribution == "CentOS"
     loop:
       - chrony
       - wget
       - nano
       - git
       - zip
       - unzip

   - name: Install multiple packages on Ubuntu
     apt:
       name: '{{item}}'
       state: present
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
     loop:
       - ntp
       - wget
       - nano
       - git
       - zip
       - unzip
